curva_historica:
  CCPEDS: "11/12/2025"
  CCPSS: "11/12/2025"
  CCPVS: "11/12/2025"
  CSBCRD: "11/12/2025"
  CCCLD: "11/12/2025"
  CBCRS: "11/12/2025"
  CCSDF: "11/12/2025"
  CBCRPS: "11/12/2025"
  CCINFS: "11/12/2025"


indice_spreads_corporativos:
  CCCLD: "10/10/2025"
  CCPSS: "05/12/2025"
  CCPVS: "05/12/2025"
  CSBCRD: "05/12/2025"

vp_rentafija:
  rf: "05/12/2025"


  