curva_historica:
  CCPEDS: "26/12/2025"
  CCPSS: "26/12/2025"
  CCPVS: "26/12/2025"
  CSBCRD: "26/12/2025"
  CCCLD: "26/12/2025"
  CBCRS: "26/12/2025"
  CCSDF: "26/12/2025"
  CBCRPS: "26/12/2025"
  CCINFS: "26/12/2025"


indice_spreads_corporativos:
  CCCLD: "10/10/2025"
  CCPSS: "05/12/2025"
  CCPVS: "05/12/2025"
  CSBCRD: "05/12/2025"

vp_rentafija:
  rf: "05/12/2025"


  